name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Bicep
        run: |
          az deployment group create \
            --resource-group poc-rg \
            --template-file bicep/main.bicep \
            --parameters @bicep/${{ github.event.inputs.environment }}.bicepparam
#      - name: Deploy Bicep
#        run: |
#          az deployment group create \
#            --resource-group ${{ secrets.AZURE_RG }} \
#            --template-file bicep/main.bicep \
#            --parameters environmentName=${{ vars.ENVIRONMENT }} \
#                         projectName=${{ vars.PROJECT_NAME }} \
#                         location=${{ vars.LOCATION }}